server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  application:
    name: AUTH-SERVICE
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1098580004709-ur38elak0t7i9c8gvmnunchhkpjje4dm.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  secret: EEQLjAtCuNXlnTiKAvGxrWOeNAQ1vDUFwYo9w2kmAzIPY8U/7bjeyUGEb4GKAgD3xZVVZtjM3zXibMWHndfU8A==
  accessToken:
    expiration: 900000
  refreshToken:
    expiration: 86400000

security:
  password:
    encoder:
      strength: 12

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    org.springframework.security: DEBUG
    com.securitybanking: DEBUG

