server:
  port: 8082

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://localhost:3306/accountdb?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none       # Flyway va gérer le schéma, donc laissez toujours ddl-auto à "none" en production
    show-sql: true         # Active logging SQL
    open-in-view: false    # Empêche les problèmes de session Hibernate v
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        hbm2ddl.auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    out-of-order: true
    baseline-version: 0

feign:
  client:
    config:
      notification-service:
        url: http://localhost:8084

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG

app:
  jwt:
    secret-key: "mySecretKey123456789012345678901234567890" # Changez en production
    expiration: 86400000 # 24 heures en millisecondes
    refresh-expiration: 604800000 # 7 jours
    issuer: "banking-service"